#!/usr/bin/env bash

# generate zipf distribution
utils/zipf $1 100 10000 > ../data/zipf1.dist
utils/zipf $1 100 10000 > ../data/zipf2.dist

# run analysis
Rscript scripts/samples.R
make
./predict
Rscript scripts/visualize.R
Rscript scripts/fitting.R

